### PR TITLE
Simplify toggle

### PR DESCRIPTION
**Pull request by mvaivre**
Quick fix that keeps the animation, remove a variable and fixes the alignment issues.

image

### CODE REVIEW

**Comment by nop33** [comment]
By the way, I noticed that in the explorer the theme toggle looks aligned (and has animation) 😉

**Comment by mvaivre** [comment]
> By the way, I noticed that in the explorer the theme toggle looks aligned (and has animation) 😉

Yeah, it seems that it was mostly due to a pixel rounding issue. If you look closely at previous commits, the toggle in the header looked aligned whereas the exact same component in the settings looked miss-aligned (or the other way around). This should make it more predictable.

**Review by nop33 — APPROVED** [review]
Seems to work well 👏

One thing I have noticed (probably not related to this PR) is that the cursor doesn't change to a pointer always... It's quite unpredictable...

https://user-images.githubusercontent.com/1579899/167589846-0c5d87f4-9bd2-4c72-bf98-84bca32ca505.mp4

**Comment by mvaivre** [comment]
Yes, it's covered by the "invisible header" that allows for dragging the window. I witnessed the same thing in other electron apps in the past.. Didn't find a quick way to fix it so far.

**Comment by nop33** [comment]
> Yes, it's covered by the "invisible header" that allows for dragging the window. 

AHAAAA

**Pull request merged**
