### PR TITLE
Italian language

### PR DESCRIPTION
**Pull request by RedoKazda**
Hello dear team, I am your supporter, I love the Alephium project.

I created the Italian translation for the desktop wallet.

A greeting.

### CODE REVIEW

**Review by nop33 — COMMENTED** [review]
Good job @RedoKazda !

Could you please add `it-IT` to the `Language` type in https://github.com/alephium/desktop-wallet/blob/master/src/types/settings.d.ts#L50?

**Comment by nop33** [comment]
Thanks! Did you push? I don't see a new commit in your branch.

**Comment by nop33** [comment]
Thanks @RedoKazda!

Could you also please run `npm run lint:fix` to fix the linting errors? Then we're good!

**Comment by RedoKazda** [comment]
Sorry but I'm not expert on github.

I did this, downloaded github desktop for windows, then logged into my account from software for desktop, downloaded the repository and installed git on windows.
Then I opened a command prompt via github desktop, entered npm run lint:fix and it gave me this message:
"npm" is not recognized as an internal or external command,
  an executable program or batch file.

Maybe this is not doing the right thing.
Could you explain to me what I have to do? Not how can I fix this problem you told me.

**Comment by nop33** [comment]
Hey @RedoKazda thanks for explaining your process! Don't worry about it, I'll take care of it. I'll close this PR in favor of https://github.com/alephium/desktop-wallet/pull/780. All your work is included there, together with my commit to fix the linting error. Thanks for your work! 🙏

**Comment by RedoKazda** [comment]
Thank you so much for your help. Will I always be able to update this translation in the future? Thank you.

**Comment by nop33** [comment]
Yes, you will!

**Pull request closed without merging**
