### PR TITLE
Create bg-BG

### PR DESCRIPTION
**Pull request by MontaiLL**
I translated the wallet into Bulgarian :)

### CODE REVIEW

**Comment by Sakrecoer** [comment]
Thank you very much @MontaiLL! For quality assurance, it is important that we get a second opinion regarding the spelling and formulation. No one in the team is able to do this in Bulgarian. Are you able to request a review from a friend or an acquaintance? I will be on the look out for a reviewer as well :)

**Comment by nop33** [comment]
Any updates on this one? :)

**Comment by MontaiLL** [comment]
Not really... we still cannot find someone to properly verify it.

**Comment by nop33** [comment]
Superseded by https://github.com/alephium/desktop-wallet/pull/707

Closing

**Pull request closed without merging**
