### PR TITLE
Added Indonesian Translation

### PR DESCRIPTION
**Pull request by ykris45**
Hello My Name is Chris from The Republic of Indonesia. I have succeeded in translating the Alephium wallet into Indonesian as the national language of my country. I have worked as a software translator on various projects for 5 years. Thank You

### CODE REVIEW

**Comment by nop33** [comment]
Very good job @ykris45, I can see that you read the README file and I'm very happy you enabled the language! 👏 

Our team does not have anyone who speaks the language to verify the translations. Would it be possible for you to have someone have a look at your work and give us a confirmation that it's correct?

Thanks!

**Comment by ykris45** [comment]
> Very good job @ykris45, I can see that you read the README file and I'm very happy you enabled the language! 👏
> 
> Our team does not have anyone who speaks the language to verify the translations. Would it be possible for you to have someone have a look at your work and give us a confirmation that it's correct?
> 
> Thanks!

i  doesnt have someone to take a look my translation. so is very fine, i am as native indonesian speakers. and has successfully translated LBRY app to Bahasa indonesia a year ago

**Comment by mvaivre** [comment]
Great job @ykris45. We don't have any direct way to verify the content except Deepl, which seems to show that your translations are on point! 👌 Thank you!

**Comment by ykris45** [comment]
> Great job @ykris45. We don't have any direct way to verify the content except Deepl, which seems to show that your translations are on point! 👌 Thank you!

you welcome sir. lets verify with DeepL or Merge this PR with full of love. FYI my translations is based on Indonesia standart language rules.

**Review by nop33 — APPROVED** [review]

**Comment by ykris45** [comment]
@nop33 thanks you so much my special ALPH Developer team for merge my pull request

**Pull request merged**
