### PR TITLE
Simplify and improve chart animations

### PR DESCRIPTION
**Pull request by mvaivre**

### CODE REVIEW

**Review by nop33 — COMMENTED** [review]
Hm, these changes introduce a lag when opening the Address Details modal... I believe this is due to the removal of 

```ts
onAnimationComplete={(variant) => setShouldMountChart(variant === 'shown')}
```

I think I liked it more before, the UI felt more fluid and responsive.

**Comment by mvaivre** [comment]
> I think I liked it more before, the UI felt more fluid and responsive.

I have the opposite experience 🙃 Do you have your dev tools open?

**Comment by nop33** [comment]
oh, that's interesting! I don't get the lag with devtools closed! nice!

**Comment by mvaivre** [comment]
For me it's actually more fluid with this approach compared to before. Do you feel the same (with dev tools closed)?

**Review by nop33 — APPROVED** [review]

**Pull request merged**
