### PR TITLE
Switch from tinycolor2 to colord

### PR DESCRIPTION
**Pull request by LeeAlephium**
Resolves https://github.com/alephium/desktop-wallet/issues/346

### CODE REVIEW

**Comment by mvaivre** [comment]
Hover color seems broken :

**Comment by LeeAlephium** [comment]
Just for notes: turns out even though the colord API *appears* the same, the input values are actually quite different.

**Comment by LeeAlephium** [comment]
@mvaivre I've made the coloring behavior for the expand button a bit more nuanced so that the best results appear for light and dark modes

Things should be good now

**Review by mvaivre — APPROVED** [review]
LGTM

**Pull request merged**
