### PR TITLE
Fix address card being cutoff

### PR DESCRIPTION
**Pull request by LeeAlephium**
Resolves https://github.com/alephium/desktop-wallet/issues/348

### CODE REVIEW

**Comment by mvaivre** [comment]
One more issue that can be fixed in that PR:
https://github.com/alephium/desktop-wallet/issues/348#issuecomment-1238962310

**Comment by LeeAlephium** [comment]
In this branch it is centered, but the address-badge branch it isn't :thinking:

**Comment by mvaivre** [comment]
The cutoff is indeed fixed! I now notice a global horizontal overflow though: 

https://user-images.githubusercontent.com/6715943/189698291-5df1174f-5fa1-42f5-9972-15dccfb7f79e.mov

**Comment by LeeAlephium** [comment]
Is this fullscreen or something? Very odd!

**Comment by mvaivre** [comment]
It happens with any window size

**Comment by LeeAlephium** [comment]
Show/hide logic was being applied to all custom parts of the scrollbar; fixed by applying only to wrapper, should be good now @mvaivre

**Comment by mvaivre** [comment]
image

It appears that addresses are back to being cut :/

**Comment by LeeAlephium** [comment]
@mvaivre it should be squashed once again... :foot:

**Comment by nop33** [comment]
I don't notice this problem anymore on the 1.4.0 branch.

**Comment by nop33** [comment]
Looks like tests fail, maybe something wrong with rebase?

**Comment by LeeAlephium** [comment]
Yeah, there was a mistake made, all being resolved :+1:

**Review by nop33 — APPROVED** [review]
Applied my feedback already in the #369 PR, once that's merged, all good on my side 👍

**Pull request merged**
