### PR TITLE
[v2.0] Improve display of unknown tokens throughout the app

### LINKED ISSUE #556: AssetList: allow to show/hide unknown tokens
We should :

1) Display unknown tokens properly (use a hash instead of a name, use no ticker etc.)
2) Allow to show or hide unknown token by default. It should probably be shown by default(?)

### PR DESCRIPTION
**Pull request by nop33**
Closes #556

### Asset list

- Instead of a logo, display a `?`
- Instead of name, display `Unknown token`
- Instead of symbol, display copy-able token hash
- Instead of symbol next to amount, display nothing, and show the text `Raw amount` below it

image

### Transaction list
- Instead of logo and symbol, simply display the number of unknown tokens (should we add a tooltip that says `5 unknown tokens`?)
 
image

### Transaction details modal

- do not display amounts of unknown tokens in the header and instead list then in a separate section in the bottom
- instead of token symbol next to amount, show copy-able token hash

image

### Address cards

- Instead of symbol, follow similar approach with transaction list

image

### Asset select

image

### CODE REVIEW

**Comment by mvaivre** [comment]
Awesome 🚀 

> Instead of logo and symbol, simply display the number of unknown tokens (should we add a tooltip that says 5 unknown tokens?)

After trying this on the explorer, I'm leaning towards showing only the symbols (remove the asset tickers) with the hash shown in a tooltip. WDYT?

**Comment by nop33** [comment]
> After trying this on the explorer, I'm leaning towards showing only the symbols (remove the asset tickers) with the hash shown in a tooltip. WDYT?

Happy to implement that! But do you like the approach of the `(+5)` for unknown tokens?

**Comment by mvaivre** [comment]
> Happy to implement that! But do you like the approach of the (+5) for unknown tokens?

That's a good question. I think that I'd show the 5 "?" logos. It makes it easier to judge the quantity of assets exchanged while you scroll quickly + I don't think that it's be frequent that 1 TX moves that many assets at the same time, but I may be wrong.

**Comment by nop33** [comment]
Hm, ok, I'll go with that.

**Comment by mvaivre** [comment]
Thanks for all the tries :) My favorites are... the ghost (a touch of fun 👌), the "?" and the circle. 
Your favorite makes me feel like an icon isn't loading properly 😅

**Comment by nop33** [comment]
Fair enough! I can update the PR tmr to add the ghost if you agree!

**Comment by nop33** [comment]
@mvaivre Ready for review again! :)

**Review by mvaivre — APPROVED** [review]
LGTM!

**Pull request merged**
