### PR TITLE
enhance Vietnamese translation

### PR DESCRIPTION
**Pull request by nit27**
I just made an improvement of Vietnamese translation for next release at commit b1f145a6c9c05179a8581a732f0ed7737dc6eb0b

feel free to discuss :-)

### CODE REVIEW

**Comment by nop33** [comment]
@nit27 thank you for this contribution!

I noticed that the master branch of your repository is not rebased on the master branch of our repository. This is probably because it was not updated with the new placeholder translation strings that were added between the first contribution that you made and now. That's why GitHub says that this branch has conflicts. To avoid this situation, before making contributions, always ensure to be up to date with the current master of our repo (either by creating a new feature branch or updating your master branch). Is this helpful, or more confusing for you?

/cc @Sakrecoer, I am tagging you for the language verification procedure that you mentioned.

**Comment by nit27** [comment]
> 

Oh I am sorry and note it. Thanks for your advice @nop33. Do I need to re-process the procedure to achive the commit?

**Comment by nop33** [comment]
If it's not a big problem for you, it would make it easier for me to integrate it. But if it's too much hassle, I'll do it when I get the time. Thanks!

**Comment by nop33** [comment]
@nit27 I rebased your branch on top of master and opened a new PR: https://github.com/alephium/desktop-wallet/pull/536

Closing this one.

**Pull request closed without merging**
