### PR TITLE
Add More Fiat Currency options on Alephium Wallet 

### PR DESCRIPTION
**Pull request by ykris45**
Hello, i add three fiat currencies in to Alph Wallet.

1. Turkiye Lira
2. Russian Ruble
3. Vietnamese Dong
Thanks You So Much!

### CODE REVIEW

**Comment by nop33** [comment]
Hm, what about only adding currencies for countries that we support the language? Does that make sense?

**Comment by ykris45** [comment]
> Hm, what about only adding currencies for countries that we support the language? Does that make sense?

yes it makes sense. did I re-edit and only added 3 currencies

**Comment by ykris45** [comment]
@nop33 can you help to fix my unit test errors. i formated with prettier but its doesnt works.

**Comment by ykris45** [comment]
@nop33 done, 3 currencies

**Review by nop33 — APPROVED** [review]
Thanks for adding these 3! FYI, to enable then, you also need to add them in this file: https://github.com/alephium/desktop-wallet/blob/master/src/utils/settings.ts#L45-L50

I'll take care of that for now! Cheers!

**Pull request merged**
