### PR TITLE
Migrate react-router from v5 to v6

### PR DESCRIPTION
**Pull request by lf94**
Resolves https://github.com/alephium/desktop-wallet/issues/69

### CODE REVIEW

**Comment by lf94** [comment]
This one is going to need some comprehensive clicking around to make sure all paths are still working; I tried myself but it's possible I missed something.

**Review by nop33 — CHANGES_REQUESTED** [review]
Nice job!

I noticed that the back buttons in create/import wallet screens do not work.

**Review by nop33 — COMMENTED** [review]
Spot the problem :P

image

When this is fixed, all good!

**Comment by LeeAlephium** [comment]
@nop33 should be good now

**Review by mvaivre — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
