### PR TITLE
Make the theme switcher icons more aligned

### PR DESCRIPTION
**Pull request by lf94**
Resolves https://github.com/alephium/desktop-wallet/issues/209

This one was not fun to do.

### CODE REVIEW

**Review by nop33 — COMMENTED** [review]
The alignment seems perfect now 👌 

However, the animation is gone... look at this diff of before and after:

https://user-images.githubusercontent.com/1579899/167389093-a15c4396-32e7-44a3-ad93-dc3b35d141c5.mp4

**Comment by nop33** [comment]
But but but... animations are nice 😅 I can't spend time on it atm, I am focus on redux and the mobile wallet. I don't like the idea of merging a PR that fixes one problem, but introduces another task... :/

**Comment by lf94** [comment]
You can take over then if you feel that strongly about the issue it introduces :slightly_smiling_face:

**Comment by mvaivre** [comment]
This PR broke the toggles.

image

I'll take a look, and see if I can find a solution to the animation + size changes.

**Comment by mvaivre** [comment]
I've pushed a fix in #240

**Comment by lf94** [comment]
Aieee, didn't notice it was used elsewhere. Thanks @mvaivre

**Pull request closed without merging**
