### PR TITLE
Dont use the same centered modal for the password confirmation

### PR DESCRIPTION
**Pull request by LeeAlephium**
Resolves https://github.com/alephium/desktop-wallet/issues/390

### CODE REVIEW

**Comment by nop33** [comment]
@LeeAlephium thanks for the quick fix! I noticed that the same problem occurs on the second screen (`SendModalCheckTransaction`) , it's just less visible because the heights of the first and second screen are similar.

**Comment by nop33** [comment]
@LeeAlephium so maybe it'd be better for every step to have its own `CenteredModal`? I guess we can keep the same component logic, except the render method that can be modified to reflect something like that:
```
{ step === 1 && <CenteredModal ...><SendModalTransactionForm ...>...</SendModalTransactionForm></CenteredModal>
{ step === 2 && <CenteredModal ...><SendModalCheckTransaction ...>...</SendModalCheckTransaction></CenteredModal>
{ step === 3 && <CenteredModal ...><PasswordConfirmation ...>...</PasswordConfirmation></CenteredModal>
```

WDYT?

**Comment by nop33** [comment]
@LeeAlephium will you update the PR to remove the first commit since it's not needed?

**Comment by LeeAlephium** [comment]
The first commit also resolves a bug where the user closes the password modal and it closes and resets the whole Send process - not sure if that's intentional, if feels wrong for it to happen

**Review by nop33 — APPROVED** [review]

**Pull request merged**
