### PR TITLE
[v2.0] Delete contact

### LINKED ISSUE #651: Delete contacts

### PR DESCRIPTION
**Pull request by nop33**
Closes #651

### CODE REVIEW

**Comment by mvaivre** [comment]
Very nice. However I'd open a small confirmation modal on deletion, asking "Are you sure you want to remove {{ contactName }} from your contact list?". As it is now, it's easy to misfire and delete by mistake. WDYT?

**Comment by nop33** [comment]
I think you are right!

**Comment by nop33** [comment]
tadaaaa

image

**Comment by mvaivre** [comment]
Thanks 🙏
Could you make the modal a tad less wide (narrow prop I think?)? And then we'll be good to merge!

**Comment by nop33** [comment]
Done! 
image

**Review by mvaivre — APPROVED** [review]
💪

**Comment by nop33** [comment]
oops, I was slightly faster than the approval 😅

**Pull request merged**
