### PR TITLE
Thin sidebar navigation and initial notifications modal

### PR DESCRIPTION
**Pull request by nop33**
image

image

### CODE REVIEW

**Comment by mvaivre** [comment]
Great start, thanks a lot! ✨ 

One first cosmetic thing: the nav bar isn't `fixed` for now, it moves up when the page is scrollable:
image

_Continuing the review..._

**Comment by nop33** [comment]
Thanks for noticing this!

**Review by mvaivre — APPROVED** [review]
Code review done 👌 LGTM

**Comment by nop33** [comment]
The "cosmetic" issue that you noticed is quite fundamental XD We are using `z-index` a lot in our app... Which lead me to read about `stacking contexts`, and man... even though I've been doing frontend for 10 years, I feel like I barely know anything 😅 

https://www.joshwcomeau.com/css/stacking-contexts/

**Comment by nop33** [comment]
> BTW while we're here: when using flex, the order property can save lives.

💯 

It took me WAY longer to fix this "cosmetic" thing 😆 I ended up refactoring many things in the app, mainly the positioning of panels (main section, banner section, sidebar, header, scrollable content...). I also took the opportunity to clean up a lot of our z-indexes. Instead of having `-1`, `0`, `1`, `2`, `900`, `1000`, `1001`, `1002`, `10001`, `10002`, we now have only `1` and `2`. I achieved that with changing the order of elements and creating stacking contexts only when needed. Of course, I might have missed something (our app has grown quite big 👶🥺❤️), but I'm confident will solve everything before releasing 2.0 :)

I'll merge this one and create a new PR so that you don't have to re-review stuff you already reviewed.

**Pull request merged**
